name: Flutter CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main #

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configura o Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      # Instala as dependências
      - name: Install dependencies
        run: flutter pub get

      # Executa os testes
      - name: Run tests
        run: flutter test

      # Opcional: Verifica se há erros no código
      - name: Analyze code
        run: flutter analyze
